# Generated by Django 4.0.3 on 2022-03-13 16:56

from django.db import migrations, models
import supplier.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to=supplier.models.upload_photo, validators=[supplier.models.validate_photo])),
                ('created_date', models.DateField(blank=True)),
            ],
        ),
    ]
