# Generated by Django 4.0.3 on 2022-03-13 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('item', '__first__'),
        ('table', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=10, unique=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Billed'), (3, 'Cancelled')], default=1, help_text='1=Pending,2=Billed,3=Cancelled')),
                ('date_ad', models.DateField(blank=True)),
                ('time', models.TimeField(blank=True)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='table.table')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sale_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('qty', models.PositiveIntegerField()),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='order.ordermain')),
            ],
        ),
    ]
